# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smh2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=7)),
            ],
        ),
    ]
