# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smh2', '0003_tenk_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='stock',
            name='adjcloseprice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='closeprice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='openprice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text_polarity',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text_subjectivity',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
