# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tweetAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=140)),
                ('cleaned_tweet', models.CharField(max_length=140)),
                ('text_character_count', models.IntegerField()),
                ('textblob_senitment_polarity', models.DecimalField(decimal_places=10, max_digits=12)),
                ('textblob_senitment_subjectivity', models.DecimalField(decimal_places=7, max_digits=8)),
                ('flesch_kincaid', models.DecimalField(decimal_places=3, max_digits=6)),
                ('coleman_liau_index', models.DecimalField(decimal_places=3, max_digits=6)),
                ('flesch_reading_ease', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fog', models.DecimalField(decimal_places=7, max_digits=9)),
                ('impact', models.CharField(max_length=50)),
                ('percent_change', models.DecimalField(decimal_places=28, max_digits=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
